# Generated by Django 3.1.5 on 2021-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210303_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='winnner',
            new_name='winner',
        ),
    ]
